package com.pets.enums;

public enum PetBreed {

    GOLDEN_RETRIEVER, LABRADOR, PUG, DALMATION, POODLE, PIT_BULL, SIBERIAN_HUSKY,
    GERMAN_SHEPHERD, BOXER, AuSTRALIAN_SHEPHERD, SIAMESE, PERSIAN, MAINE_COON, RAGDOLL,
    BENGAL, ABYSSINIAN, BIRMAN, AMERICAN_SHORTHAIR, AMERICAN_CURL, BRAHMAN, AYRSHIRE,
    JERSEY, HOLSTEIN_FRIESIAN, HIGHLAND, LIMOUSIN, MALVI, BROWN_SWISS, GELBVIEH, DROUGHTMASTER,
    AMERICAN_CROW, BALD_EAGLE, CANARY, DUCK, EAGLE_OWL, FALCON, GOLDEN_EAGLE, HAWK, IBIS,
    JAY, KIWI, LARK, MACAW, NIGHTINGALE, OSTRICH, PELICAN, QUAIL, ROBIN, SPARROW, TURKEY,
    UMBRELLA_COCKATOO, VULTURE, WOODPECKER, XENOPS, YELLOW_WARBLER, ZEBRA_DOVE

}

